# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c879cced2643c702bac3a0d29468e12d55f36cfbe8d043cfe28be3bb32d2dea806f6716c826b15cefb3d38732ebb871673464a956849a35956225435b8269ec5

test:
  secret_key_base: 5130bb6952bc91170fe073f85fc03fb301bb06d4dbee8a97fed7a6519f44b68d5349623d46532c719cd5df7c78a65cb61a28754f3d6f6c1d40f29626b0ccbb8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
